In [1]:
# Import dependencies
import pandas as pd
import numpy as np

In [2]:
# Import data
file_path = "uszips.csv"
# Drop index
zip_data_df = pd.read_csv(file_path, index_col= 0)
zip_data_df.head(10)

,lat,lng,city,state_id,state_name,zcta,parent_zcta,population,density,county_fips,county_name,county_weights,county_names_all,county_fips_all,imprecise,military,timezone
zip,,,,,,,,,,,,,,,,,
601,18.18005,-66.75218,Adjuntas,PR,Puerto Rico,True,NaN,17113.0,102.7,72001,Adjuntas,"{""72001"": ""99.43"", ""72141"": ""0.57""}",Adjuntas|Utuado,72001|72141,False,False,America/Puerto_Rico
602,18.36074,-67.17519,Aguada,PR,Puerto Rico,True,NaN,37751.0,476.0,72003,Aguada,"{""72003"": ""100""}",Aguada,72003,False,False,America/Puerto_Rico
603,18.45440,-67.12201,Aguadilla,PR,Puerto Rico,True,NaN,47081.0,574.9,72005,Aguadilla,"{""72005"": ""100""}",Aguadilla,72005,False,False,America/Puerto_Rico
606,18.16721,-66.93828,Maricao,PR,Puerto Rico,True,NaN,6392.0,58.3,72093,Maricao,"{""72093"": ""94.88"", ""72153"": ""3.78"", ""72121"": ""...",Maricao|Yauco|Sabana Grande,72093|72153|72121,False,False,America/Puerto_Rico
610,18.29032,-67.12244,Anasco,PR,Puerto Rico,True,NaN,26686.0,286.9,72011,Añasco,"{""72011"": ""99.45"", ""72003"": ""0.55""}",Añasco|Aguada,72011|72003,False,False,America/Puerto_Rico
612,18.40699,-66.70805,Arecibo,PR,Puerto Rico,True,NaN,59369.0,339.1,72013,Arecibo,"{""72013"": ""99.89"", ""72017"": ""0.11""}",Arecibo|Barceloneta,72013|72017,False,False,America/Puerto_Rico
616,18.41752,-66.66814,Bajadero,PR,Puerto Rico,True,NaN,10022.0,335.6,72013,Arecibo,"{""72013"": ""100""}",Arecibo,72013,False,False,America/Puerto_Rico
617,18.44125,-66.55916,Barceloneta,PR,Puerto Rico,True,NaN,23750.0,603.5,72017,Barceloneta,"{""72017"": ""99.43"", ""72054"": ""0.57""}",Barceloneta|Florida,72017|72054,False,False,America/Puerto_Rico
622,17.99174,-67.15248,Boqueron,PR,Puerto Rico,True,NaN,6741.0,89.8,72023,Cabo Rojo,"{""72023"": ""100""}",Cabo Rojo,72023,False,False,America/Puerto_Rico
623,18.08354,-67.15418,Cabo Rojo,PR,Puerto Rico,True,NaN,41746.0,424.5,72023,Cabo Rojo,"{""72023"": ""100""}",Cabo Rojo,72023,False,False,America/Puerto_Rico

In [3]:
# Column types
zip_data_df.dtypes

lat                 float64
lng                 float64
city                 object
state_id             object
state_name           object
zcta                   bool
parent_zcta         float64
population          float64
density             float64
county_fips           int64
county_name          object
county_weights       object
county_names_all     object
county_fips_all      object
imprecise              bool
military               bool
timezone             object
dtype: object

In [4]:
# Row count
zip_data_df.count()

lat                 33120
lng                 33120
city                33120
state_id            33120
state_name          33120
zcta                33120
parent_zcta             0
population          33096
density             33096
county_fips         33120
county_name         33120
county_weights      33120
county_names_all    33120
county_fips_all     33120
imprecise           33120
military            33120
timezone            33120
dtype: int64

In [5]:
# Drop all states save Michigan
zip_data_df.drop(zip_data_df.index[zip_data_df['state_name'] != "Michigan"], inplace = True)
zip_data_df

,lat,lng,city,state_id,state_name,zcta,parent_zcta,population,density,county_fips,county_name,county_weights,county_names_all,county_fips_all,imprecise,military,timezone
zip,,,,,,,,,,,,,,,,,
48001,42.63776,-82.57960,Algonac,MI,Michigan,True,NaN,11903.0,241.5,26147,St. Clair,"{""26147"": ""100""}",St. Clair,26147,False,False,America/Detroit
48002,42.93908,-82.92600,Allenton,MI,Michigan,True,NaN,3224.0,33.5,26147,St. Clair,"{""26147"": ""100""}",St. Clair,26147,False,False,America/Detroit
48003,42.93259,-83.04065,Almont,MI,Michigan,True,NaN,6047.0,70.8,26087,Lapeer,"{""26087"": ""100""}",Lapeer,26087,False,False,America/Detroit
48005,42.85024,-82.92310,Armada,MI,Michigan,True,NaN,5509.0,58.3,26099,Macomb,"{""26099"": ""100""}",Macomb,26099,False,False,America/Detroit
48006,43.07539,-82.69647,Avoca,MI,Michigan,True,NaN,4058.0,21.9,26147,St. Clair,"{""26147"": ""100""}",St. Clair,26147,False,False,America/Detroit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49967,46.49554,-88.93683,Trout Creek,MI,Michigan,True,NaN,458.0,0.5,26131,Ontonagon,"{""26131"": ""66.46"", ""26061"": ""26.63"", ""26071"": ...",Ontonagon|Houghton|Iron,26131|26061|26071,False,False,America/Detroit
49968,46.49227,-89.89300,Wakefield,MI,Michigan,True,NaN,1942.0,3.0,26053,Gogebic,"{""26053"": ""100""}",Gogebic,26053,False,False,America/Menominee
49969,46.24630,-89.22106,Watersmeet,MI,Michigan,True,NaN,1259.0,1.9,26053,Gogebic,"{""26053"": ""100""}",Gogebic,26053,False,False,America/Menominee
49970,46.54120,-88.60494,Watton,MI,Michigan,True,NaN,292.0,1.1,26013,Baraga,"{""26013"": ""100""}",Baraga,26013,False,False,America/Detroit
49971,46.67711,-89.70132,White Pine,MI,Michigan,True,NaN,478.0,2.0,26131,Ontonagon,"{""26131"": ""100""}",Ontonagon,26131,False,False,America/Detroit

In [6]:
# Drop duplicates
zip_data_df.drop_duplicates()

,lat,lng,city,state_id,state_name,zcta,parent_zcta,population,density,county_fips,county_name,county_weights,county_names_all,county_fips_all,imprecise,military,timezone
zip,,,,,,,,,,,,,,,,,
48001,42.63776,-82.57960,Algonac,MI,Michigan,True,NaN,11903.0,241.5,26147,St. Clair,"{""26147"": ""100""}",St. Clair,26147,False,False,America/Detroit
48002,42.93908,-82.92600,Allenton,MI,Michigan,True,NaN,3224.0,33.5,26147,St. Clair,"{""26147"": ""100""}",St. Clair,26147,False,False,America/Detroit
48003,42.93259,-83.04065,Almont,MI,Michigan,True,NaN,6047.0,70.8,26087,Lapeer,"{""26087"": ""100""}",Lapeer,26087,False,False,America/Detroit
48005,42.85024,-82.92310,Armada,MI,Michigan,True,NaN,5509.0,58.3,26099,Macomb,"{""26099"": ""100""}",Macomb,26099,False,False,America/Detroit
48006,43.07539,-82.69647,Avoca,MI,Michigan,True,NaN,4058.0,21.9,26147,St. Clair,"{""26147"": ""100""}",St. Clair,26147,False,False,America/Detroit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49967,46.49554,-88.93683,Trout Creek,MI,Michigan,True,NaN,458.0,0.5,26131,Ontonagon,"{""26131"": ""66.46"", ""26061"": ""26.63"", ""26071"": ...",Ontonagon|Houghton|Iron,26131|26061|26071,False,False,America/Detroit
49968,46.49227,-89.89300,Wakefield,MI,Michigan,True,NaN,1942.0,3.0,26053,Gogebic,"{""26053"": ""100""}",Gogebic,26053,False,False,America/Menominee
49969,46.24630,-89.22106,Watersmeet,MI,Michigan,True,NaN,1259.0,1.9,26053,Gogebic,"{""26053"": ""100""}",Gogebic,26053,False,False,America/Menominee
49970,46.54120,-88.60494,Watton,MI,Michigan,True,NaN,292.0,1.1,26013,Baraga,"{""26013"": ""100""}",Baraga,26013,False,False,America/Detroit
49971,46.67711,-89.70132,White Pine,MI,Michigan,True,NaN,478.0,2.0,26131,Ontonagon,"{""26131"": ""100""}",Ontonagon,26131,False,False,America/Detroit

In [7]:
# Check for populations with 0
zip_data_df.sort_values(["population"], ascending=True)

,lat,lng,city,state_id,state_name,zcta,parent_zcta,population,density,county_fips,county_name,county_weights,county_names_all,county_fips_all,imprecise,military,timezone
zip,,,,,,,,,,,,,,,,,
48710,43.55649,-83.98781,University Center,MI,Michigan,True,NaN,0.0,0.0,26017,Bay,"{""26017"": ""0""}",Bay,26017,False,False,America/Detroit
48397,42.49501,-83.04105,Warren,MI,Michigan,True,NaN,0.0,0.0,26099,Macomb,"{""26099"": ""0""}",Macomb,26099,False,False,America/Detroit
48143,42.45982,-83.85196,Lakeland,MI,Michigan,True,NaN,0.0,0.0,26093,Livingston,"{""26093"": ""100""}",Livingston,26093,False,False,America/Detroit
48667,43.60217,-84.23409,Midland,MI,Michigan,True,NaN,0.0,0.0,26111,Midland,"{""26111"": ""0""}",Midland,26111,False,False,America/Detroit
48551,42.98103,-83.71691,Flint,MI,Michigan,True,NaN,0.0,0.0,26049,Genesee,"{""26049"": ""0""}",Genesee,26049,False,False,America/Detroit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48103,42.25991,-83.84325,Ann Arbor,MI,Michigan,True,NaN,55118.0,327.0,26161,Washtenaw,"{""26161"": ""100""}",Washtenaw,26161,False,False,America/Detroit
48228,42.35545,-83.21705,Detroit,MI,Michigan,True,NaN,56262.0,2523.0,26163,Wayne,"{""26163"": ""100""}",Wayne,26163,False,False,America/Detroit
48044,42.64991,-82.92956,Macomb,MI,Michigan,True,NaN,57745.0,1651.1,26099,Macomb,"{""26099"": ""100""}",Macomb,26099,False,False,America/Detroit
48180,42.22600,-83.26882,Taylor,MI,Michigan,True,NaN,61379.0,1003.9,26163,Wayne,"{""26163"": ""100""}",Wayne,26163,False,False,America/Detroit
48197,42.19714,-83.62885,Ypsilanti,MI,Michigan,True,NaN,68108.0,627.3,26161,Washtenaw,"{""26161"": ""100""}",Washtenaw,26161,False,False,America/Detroit

In [8]:
# Drop null population values (most are duplicates)
zip_data_df.drop(zip_data_df.index[zip_data_df['population'] == 0], inplace = True)
zip_data_df

,lat,lng,city,state_id,state_name,zcta,parent_zcta,population,density,county_fips,county_name,county_weights,county_names_all,county_fips_all,imprecise,military,timezone
zip,,,,,,,,,,,,,,,,,
48001,42.63776,-82.57960,Algonac,MI,Michigan,True,NaN,11903.0,241.5,26147,St. Clair,"{""26147"": ""100""}",St. Clair,26147,False,False,America/Detroit
48002,42.93908,-82.92600,Allenton,MI,Michigan,True,NaN,3224.0,33.5,26147,St. Clair,"{""26147"": ""100""}",St. Clair,26147,False,False,America/Detroit
48003,42.93259,-83.04065,Almont,MI,Michigan,True,NaN,6047.0,70.8,26087,Lapeer,"{""26087"": ""100""}",Lapeer,26087,False,False,America/Detroit
48005,42.85024,-82.92310,Armada,MI,Michigan,True,NaN,5509.0,58.3,26099,Macomb,"{""26099"": ""100""}",Macomb,26099,False,False,America/Detroit
48006,43.07539,-82.69647,Avoca,MI,Michigan,True,NaN,4058.0,21.9,26147,St. Clair,"{""26147"": ""100""}",St. Clair,26147,False,False,America/Detroit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49967,46.49554,-88.93683,Trout Creek,MI,Michigan,True,NaN,458.0,0.5,26131,Ontonagon,"{""26131"": ""66.46"", ""26061"": ""26.63"", ""26071"": ...",Ontonagon|Houghton|Iron,26131|26061|26071,False,False,America/Detroit
49968,46.49227,-89.89300,Wakefield,MI,Michigan,True,NaN,1942.0,3.0,26053,Gogebic,"{""26053"": ""100""}",Gogebic,26053,False,False,America/Menominee
49969,46.24630,-89.22106,Watersmeet,MI,Michigan,True,NaN,1259.0,1.9,26053,Gogebic,"{""26053"": ""100""}",Gogebic,26053,False,False,America/Menominee
49970,46.54120,-88.60494,Watton,MI,Michigan,True,NaN,292.0,1.1,26013,Baraga,"{""26013"": ""100""}",Baraga,26013,False,False,America/Detroit
49971,46.67711,-89.70132,White Pine,MI,Michigan,True,NaN,478.0,2.0,26131,Ontonagon,"{""26131"": ""100""}",Ontonagon,26131,False,False,America/Detroit

In [9]:
# Drop columns
zip_data_df.drop(columns=["lat", "lng", "state_id", "state_name", "parent_zcta", "density", "county_fips", "county_weights", 
                          "county_names_all", "county_fips_all", "imprecise", "military", "timezone"])

              city  zcta  population county_name
zip
48001      Algonac  True     11903.0   St. Clair
48002     Allenton  True      3224.0   St. Clair
48003       Almont  True      6047.0      Lapeer
48005       Armada  True      5509.0      Macomb
48006        Avoca  True      4058.0   St. Clair
...            ...   ...         ...         ...
49967  Trout Creek  True       458.0   Ontonagon
49968    Wakefield  True      1942.0     Gogebic
49969   Watersmeet  True      1259.0     Gogebic
49970       Watton  True       292.0      Baraga
49971   White Pine  True       478.0   Ontonagon

[976 rows x 4 columns]

In [10]:
# Output to CSV
zip_data_df.to_csv("zipcodes.csv")